### ISSUE TITLE
Error for a book

### ISSUE THREAD

**Issue by mehetabelo** [Mitch528/WebNovelConverter#19]
Found an error when trying to download Master of Learning. After breaking it down into chunks
Error generating Epub I discovered it's Chapter152 causing the issue. Here is the link and error report: 
http://royalroadl.com/fiction/4585

ERROR: System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_Fragment()
   at System.UriBuilder.Init(Uri uri)
   at System.UriBuilder..ctor(Uri uri)
   at Epub.Net.EBook.<EmbedImagesAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Epub.Net.EBook.<GenerateEpubAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at WebNovelConverter.MainForm.<convertBackgroundWorker_DoWork>d__9.MoveNext() in C:\WebNovelConverter\WebNovelConverter\MainForm.cs:line 215

**Comment by mehetabelo** [comment]
Oh, and is there any chance you can filter out 'Read this chapter using the new beta ...' that's posted at the top of fics now?
